// <auto-generated />
using DestifyMovies.Server.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DestifyMovies.Server.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoviesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorMovie");

                    b.HasData(
                        new
                        {
                            ActorsId = -1,
                            MoviesId = -1
                        },
                        new
                        {
                            ActorsId = -2,
                            MoviesId = -1
                        },
                        new
                        {
                            ActorsId = -3,
                            MoviesId = -1
                        },
                        new
                        {
                            ActorsId = -4,
                            MoviesId = -1
                        },
                        new
                        {
                            ActorsId = -5,
                            MoviesId = -1
                        },
                        new
                        {
                            ActorsId = -6,
                            MoviesId = -1
                        },
                        new
                        {
                            ActorsId = -7,
                            MoviesId = -1
                        },
                        new
                        {
                            ActorsId = -1,
                            MoviesId = -2
                        },
                        new
                        {
                            ActorsId = -3,
                            MoviesId = -2
                        },
                        new
                        {
                            ActorsId = -4,
                            MoviesId = -2
                        },
                        new
                        {
                            ActorsId = -5,
                            MoviesId = -2
                        },
                        new
                        {
                            ActorsId = -6,
                            MoviesId = -2
                        },
                        new
                        {
                            ActorsId = -7,
                            MoviesId = -2
                        },
                        new
                        {
                            ActorsId = -1,
                            MoviesId = -3
                        },
                        new
                        {
                            ActorsId = -3,
                            MoviesId = -3
                        },
                        new
                        {
                            ActorsId = -4,
                            MoviesId = -3
                        },
                        new
                        {
                            ActorsId = -5,
                            MoviesId = -3
                        },
                        new
                        {
                            ActorsId = -6,
                            MoviesId = -3
                        },
                        new
                        {
                            ActorsId = -7,
                            MoviesId = -3
                        },
                        new
                        {
                            ActorsId = -8,
                            MoviesId = -4
                        },
                        new
                        {
                            ActorsId = -9,
                            MoviesId = -4
                        },
                        new
                        {
                            ActorsId = -10,
                            MoviesId = -4
                        },
                        new
                        {
                            ActorsId = -11,
                            MoviesId = -4
                        },
                        new
                        {
                            ActorsId = -12,
                            MoviesId = -4
                        },
                        new
                        {
                            ActorsId = -13,
                            MoviesId = -4
                        },
                        new
                        {
                            ActorsId = -14,
                            MoviesId = -4
                        },
                        new
                        {
                            ActorsId = -8,
                            MoviesId = -5
                        },
                        new
                        {
                            ActorsId = -9,
                            MoviesId = -5
                        },
                        new
                        {
                            ActorsId = -10,
                            MoviesId = -5
                        },
                        new
                        {
                            ActorsId = -11,
                            MoviesId = -5
                        },
                        new
                        {
                            ActorsId = -13,
                            MoviesId = -5
                        },
                        new
                        {
                            ActorsId = -14,
                            MoviesId = -5
                        },
                        new
                        {
                            ActorsId = -12,
                            MoviesId = -6
                        },
                        new
                        {
                            ActorsId = -15,
                            MoviesId = -6
                        },
                        new
                        {
                            ActorsId = -16,
                            MoviesId = -6
                        },
                        new
                        {
                            ActorsId = -17,
                            MoviesId = -6
                        },
                        new
                        {
                            ActorsId = -18,
                            MoviesId = -6
                        },
                        new
                        {
                            ActorsId = -19,
                            MoviesId = -6
                        },
                        new
                        {
                            ActorsId = -20,
                            MoviesId = -6
                        },
                        new
                        {
                            ActorsId = -21,
                            MoviesId = -6
                        });
                });

            modelBuilder.Entity("DestifyMovies.Server.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            FirstName = "Daisy",
                            LastName = "Ridley"
                        },
                        new
                        {
                            Id = -2,
                            FirstName = "John",
                            LastName = "Boyega"
                        },
                        new
                        {
                            Id = -3,
                            FirstName = "Harrison",
                            LastName = "Ford"
                        },
                        new
                        {
                            Id = -4,
                            FirstName = "Oscar",
                            LastName = "Isaac"
                        },
                        new
                        {
                            Id = -5,
                            FirstName = "Adam",
                            LastName = "Driver"
                        },
                        new
                        {
                            Id = -6,
                            FirstName = "Carrie",
                            LastName = "Fisher"
                        },
                        new
                        {
                            Id = -7,
                            FirstName = "Mark",
                            LastName = "Hamill"
                        },
                        new
                        {
                            Id = -8,
                            FirstName = "Timothee",
                            LastName = "Chalamet"
                        },
                        new
                        {
                            Id = -9,
                            FirstName = "Zendaya",
                            LastName = ""
                        },
                        new
                        {
                            Id = -10,
                            FirstName = "Rebecca",
                            LastName = "Ferguson"
                        },
                        new
                        {
                            Id = -11,
                            FirstName = "Florence",
                            LastName = "Pugh"
                        },
                        new
                        {
                            Id = -12,
                            FirstName = "Jason",
                            LastName = "Momoa"
                        },
                        new
                        {
                            Id = -13,
                            FirstName = "Josh",
                            LastName = "Brolin"
                        },
                        new
                        {
                            Id = -14,
                            FirstName = "Austin",
                            LastName = "Butler"
                        },
                        new
                        {
                            Id = -15,
                            FirstName = "Amber",
                            LastName = "Heard"
                        },
                        new
                        {
                            Id = -16,
                            FirstName = "Patrick",
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = -17,
                            FirstName = "Nicole",
                            LastName = "Kidman"
                        },
                        new
                        {
                            Id = -18,
                            FirstName = "Willem",
                            LastName = "Dafoe"
                        },
                        new
                        {
                            Id = -19,
                            FirstName = "Dolph",
                            LastName = "Lundgren"
                        },
                        new
                        {
                            Id = -20,
                            FirstName = "Randall",
                            LastName = "Park"
                        },
                        new
                        {
                            Id = -21,
                            FirstName = "Michael",
                            LastName = "Beach"
                        });
                });

            modelBuilder.Entity("DestifyMovies.Server.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Title = "Star Wars Episode 7 The Force Awakens"
                        },
                        new
                        {
                            Id = -2,
                            Title = "Star Wars Episode 8 The Last Jedi"
                        },
                        new
                        {
                            Id = -3,
                            Title = "Star Wars Episode 9 The Rise of Skywalker"
                        },
                        new
                        {
                            Id = -4,
                            Title = "Dune Part 1"
                        },
                        new
                        {
                            Id = -5,
                            Title = "Dune Part 2"
                        },
                        new
                        {
                            Id = -6,
                            Title = "Aquaman"
                        });
                });

            modelBuilder.Entity("DestifyMovies.Server.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            MovieId = -1,
                            Score = 78,
                            Source = "IMDB"
                        },
                        new
                        {
                            Id = -2,
                            MovieId = -1,
                            Score = 93,
                            Source = "Rotten Tomatoes"
                        },
                        new
                        {
                            Id = -3,
                            MovieId = -1,
                            Score = 80,
                            Source = "Metacritic"
                        },
                        new
                        {
                            Id = -4,
                            MovieId = -2,
                            Score = 69,
                            Source = "IMDB"
                        },
                        new
                        {
                            Id = -5,
                            MovieId = -2,
                            Score = 91,
                            Source = "Rotten Tomatoes"
                        },
                        new
                        {
                            Id = -6,
                            MovieId = -2,
                            Score = 84,
                            Source = "Metacritic"
                        },
                        new
                        {
                            Id = -7,
                            MovieId = -3,
                            Score = 64,
                            Source = "IMDB"
                        },
                        new
                        {
                            Id = -8,
                            MovieId = -3,
                            Score = 52,
                            Source = "Rotten Tomatoes"
                        },
                        new
                        {
                            Id = -9,
                            MovieId = -3,
                            Score = 53,
                            Source = "Metacritic"
                        },
                        new
                        {
                            Id = -10,
                            MovieId = -4,
                            Score = 80,
                            Source = "IMDB"
                        },
                        new
                        {
                            Id = -11,
                            MovieId = -4,
                            Score = 83,
                            Source = "Rotten Tomatoes"
                        },
                        new
                        {
                            Id = -12,
                            MovieId = -4,
                            Score = 74,
                            Source = "Metacritic"
                        },
                        new
                        {
                            Id = -13,
                            MovieId = -5,
                            Score = 89,
                            Source = "IMDB"
                        },
                        new
                        {
                            Id = -14,
                            MovieId = -5,
                            Score = 93,
                            Source = "Rotten Tomatoes"
                        },
                        new
                        {
                            Id = -15,
                            MovieId = -5,
                            Score = 79,
                            Source = "Metacritic"
                        },
                        new
                        {
                            Id = -16,
                            MovieId = -6,
                            Score = 68,
                            Source = "IMDB"
                        },
                        new
                        {
                            Id = -17,
                            MovieId = -6,
                            Score = 66,
                            Source = "Rotten Tomatoes"
                        },
                        new
                        {
                            Id = -18,
                            MovieId = -6,
                            Score = 55,
                            Source = "Metacritic"
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("DestifyMovies.Server.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DestifyMovies.Server.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DestifyMovies.Server.Models.Rating", b =>
                {
                    b.HasOne("DestifyMovies.Server.Models.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DestifyMovies.Server.Models.Movie", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
